# Configure main menu and social menu
[[main]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/marcchehab"
[main.params]
icon = "brand-twitter"
newtab = true

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com/marcchehab"

# [social.params]
# icon = "brand-twitter"

